### ISSUE TITLE
无方会心期望与面板会心值不匹配

### ISSUE THREAD

**Issue by kaninchen499** [LynTss/jx3dps-online#15]
hello，
这边先贴图
![计算器](https://github.com/user-attachments/assets/a4d6ce3c-e85e-42e4-ac81-e579483ec75e)
![image](https://github.com/user-attachments/assets/6d4807e8-3149-4bf3-acc2-6bf96367f27b)
第一张图可以看到计算器模拟会心率38%远高于面板会心35%， 不应当是随机不确定性引发，然后再对比第二张图我打木桩的数据，这边结果也是差不多35%。 所以这边会心的计算是不是不太对呀？

Best

西方小可

**Comment by LynTss** [comment]
门派套装的断肠buff会提供会心
